"""Add interests and skills to User model

Revision ID: 3c26424a34b0
Revises: 605129403899
Create Date: 2024-10-02 22:11:12.611779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c26424a34b0'
down_revision = '605129403899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
