"""Add interests and skills to Post model

Revision ID: 605129403899
Revises: 18406a2c848d
Create Date: 2024-10-02 22:00:03.933279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605129403899'
down_revision = '18406a2c848d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
